# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from lib import detection_pb2 as detection__pb2


class MLServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predict = channel.stream_unary(
        '/MLServer/predict',
        request_serializer=detection__pb2.Chunk.SerializeToString,
        response_deserializer=detection__pb2.Reply.FromString,
        )


class MLServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def predict(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MLServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predict': grpc.stream_unary_rpc_method_handler(
          servicer.predict,
          request_deserializer=detection__pb2.Chunk.FromString,
          response_serializer=detection__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MLServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
